### Create User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "sd@a.com",
    "password": "asdsssssd"
}

### Signin User
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "sd@a.com",
    "password": "asdsssssd"
}

### Get User by id
GET http://localhost:3000/auth/2
content-type: application/json

### GET User by email
GET http://localhost:3000/auth?email=sd@a.com
content-type: application/json


### Delete User
DELETE http://localhost:3000/auth/1
content-type: application/json

### Update User
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "www@a.com"
}


### Get current signed in user
GET http://localhost:3000/auth/whoami

### signout current signed in user
POST http://localhost:3000/auth/signout